SapychevEvgenii:  Homework_4_Lesson 4
eugene-okulik/evgeniisapychev pull request #3
Opened 2024-06-04 22:31 UTC by EvgenySapychev

2024-06-07 10:46 UTC, eugene-okulik requested changes
не нашел у тебя решения вот этого:

> Для того, что хранится под ключом ‘tuple’:
выведите на экран последний элемент

2024-06-07 10:46 UTC, eugene-okulik commented on homework/sapychev_evgenii/lesson_4/lesson_4.py
> +my_dict['dict'].update({'i am a tuple': 6})
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-06-07 19:03 UTC, EvgenySapychev commented
Да, что то поторопился. Добавил проверку type, надеюсь теперь правильно. Не до конца понял как будто.

2024-06-10 09:58 UTC, eugene-okulik approved these changes

2024-06-10 09:58 UTC, merged