SapychevEvgenii: homework_5_DONE
eugene-okulik/evgeniisapychev pull request #4
Opened 2024-06-13 21:34 UTC by EvgenySapychev

2024-06-13 21:35 UTC, EvgenySapychev commented
Привет! Не до конца понял, что требуется сделать во втором задание.. Поэтому просто проиндексировал позицию чисел и добавил к результату 10. 100% не правильно, но чего-то совсем не врубился с описания.. :(

2024-06-15 14:01 UTC, eugene-okulik requested changes

2024-06-15 14:01 UTC, eugene-okulik commented on homework/sapychev_evgenii/lesson_5/lesson_5.1
> +print(name, last_name, city, phone, country)
Обращение к элементам списка по индексу - это крайняя мера и нужно пытаться этого избегать. И здесь мы можем избежать этого с помощью распаковки.

2024-06-15 14:01 UTC, eugene-okulik commented on homework/sapychev_evgenii/lesson_5/lesson_5.2.py
В примерах - варианты того, как может ответить программа. Нам нужно сделать один код, который сможет работать с любым из вариантов ответа. То есть обработать каждую переменную абсолютно одинаковым кодом. Пока что делаем это копируя код, потом будем учиться как избежать здесь этого копирования.  
Для этого нужно найти в этих строках что-то одинаковое: количество символов перед числом разное; количество символов в числе тоже разное. Но есть в структуре всех строк что-то одинаковое и на это можно опереться.  
Ну и 10 нужно прибавить не к позиции числа, а к тому числу, которое ты получишь из этой строки.

2024-06-16 21:13 UTC, EvgenySapychev commented
Привет! Спасибо за комментарии!
Вроде как я разобрался с 1. Но вот второе, все равно пришлось применить дополнительные действия... Как по мне, получилось универсально и идея вроде понятная, но пришлось применить replace, а не только индекс и срез...

2024-06-18 10:10 UTC, eugene-okulik approved these changes

2024-06-18 10:10 UTC, eugene-okulik commented on homework/sapychev_evgenii/lesson_5/lesson_5.2.py
> +print(int(a[a.index(": "):].replace(': ', '')) + 10)
Можно было вместо реплейса просто к индексу добавить 2, ведь мы знаем, что по позиции двоеточия у нас двоеточие, а число начинается через два символа от этого места. Т.е. было бы так:
```python
print(int(a[a.index(": ")  + 2:]) + 10)
```
Но твое решение тоже норм. Каждый сам выбирает для своего кода костыль, который ему больше нравится ))))

2024-06-18 10:10 UTC, merged

2024-06-18 19:01 UTC, EvgenySapychev commented on homework/sapychev_evgenii/lesson_5/lesson_5.2.py
> +print(int(a[a.index(": "):].replace(': ', '')) + 10)
Блин, и правда! Главное идею понял в итоге :) Спасибо!